#!/bin/sh
inputdir="/datasets/ndbc-small/*"
gluster="/gfs"
prefix="output-"
lastnum=$(ls $gluster$HOME |
sed -rne 's:output-([0-9]+):\1:p' |
sort -n |
tail -n1)
newnum=$(expr $lastnum \+ 1)
outputdir="$HOME/$prefix$newnum"
echo "Input dir: $inputdir"
echo "Output dir: $outputdir"
spark-submit build/spec.jar $inputdir $outputdir
